import type { Metadata } from "next";
import "./global.css"
import { CartProvider } from '@/src/context/CartContext';

export const metadata: Metadata = {
  title: "Furniro eCommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
